In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv("insurance_data.csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2, random_state=25)


In [5]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [6]:
len(X_train_scaled['age'])

22

In [7]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 0.7113 - accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 11ms/step - loss: 0.7110 - accuracy: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 8ms/step - loss: 0.7106 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 8ms/step - loss: 0.7102 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 8ms/step - loss: 0.7098 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 13ms/step - loss: 0.7094 - accuracy: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 10ms/step - loss: 0.7091 - accuracy: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 12ms/step - loss: 0.7087 - accuracy: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 12ms/step - loss: 0.7083 - accuracy: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 12ms/step - loss: 0.7079 - accuracy: 0.5000
Epoch 11/100
1/1 [======

In [8]:
model.evaluate(X_test_scaled,y_test)

1/1 [==============================] - 0s 425ms/step - loss: 0.6918 - accuracy: 0.5000


[0.6917628645896912, 0.5]

In [9]:
model.predict(X_test_scaled)

1/1 [==============================] - 0s 298ms/step


array([[0.7743649 ],
       [0.72521085],
       [0.53454727],
       [0.74288785],
       [0.7775143 ],
       [0.79574805]], dtype=float32)

In [10]:
coef,intercept=model.get_weights()
coef,intercept

(array([[0.9057445 ],
        [0.90450823]], dtype=float32),
 array([-0.09708388], dtype=float32))

In [11]:
def sigmoid(x):
    import math
    return 1/(1+math.exp(-x))

sigmoid(10)

0.9999546021312976

In [13]:
def prediction_function(age,affordibility):
    weighted_sum = coef[0]*age+ coef[1]*affordibility+intercept
    return sigmoid(weighted_sum)

In [15]:
prediction_function(.47,1)

0.7743649243286069